### ISSUE TITLE
bricked after writing openwrt dump 

### ISSUE THREAD

**Issue by faroukrmt** [Mio-sha512/openstick-stuff#1]
hello; I have bricked my msm8916 4g usb stick (UZ801 V2.1) after writing the openwrt dump from (https://github.com/Mio-sha512/openstick-stuff/releases/tag/Firmware). the stick run perfectly after writing emmc block then when i try to reboot and reflash the original software it stuck in bootloader mode and refuse to boot into edl even after shortin d+and dnd ... identified in dev manager  as android  (USB\VID_18D1&PID_D00D\1001EB3) or android bootloader interface, please help unbreak

**Comment by Mio-sha512** [comment]
Hi,

Does it boot into fastboot or adb?

**Comment by faroukrmt** [comment]
it boot into fastboot ... but cant flash or format ... and all reboot edl command not working

**Comment by Mio-sha512** [comment]
Ok, try the command `fastboot oem reboot-edl` thats what i use because shorting pins only works on the stock firmware

**Comment by faroukrmt** [comment]
![image](https://user-images.githubusercontent.com/20300548/213922466-3fb9c5e9-1872-4e46-9401-d03b51cd3bce.png)
unfortunatly ... when i try to reboot via fastboot to edl by miko too it simply reboot to bootloader again

**Comment by Mio-sha512** [comment]
Try and do `fastboot devices` or `adb devices`

**Comment by faroukrmt** [comment]
it get 
`C:\Program Files (x86)\miko_service_tool_pro\miko_service_tool_pro\adb>fastboot devices
1001eb3 fastboot

C:\Program Files (x86)\miko_service_tool_pro\miko_service_tool_pro\adb>adb devices
List of devices attached
* daemon not running. starting it now on port 5037 *
* daemon started successfully *`

**Comment by Mio-sha512** [comment]
Ok, so thats a start!

try and do `fastboot oem help`

**Comment by faroukrmt** [comment]
nothing :/
`C:\Program` Files (x86)\miko_service_tool_pro\miko_service_tool_pro\adb>fastboot oem help
...
FAILED (remote: unknown command)
finished. total time: 0.016s

**Comment by Mio-sha512** [comment]
Hmmmmmmmmm, Right now you have the openwrt flashed yes?

**Comment by faroukrmt** [comment]
yes, the problem is I mistakenly ruined the system after trying to reflash the stock rom

**Comment by Mio-sha512** [comment]
My best guess is too try and follow this, https://forum.xda-developers.com/t/guide-tool-reboot-to-edl-mode-from-fastboot-no-more-test-point-method-kenzo.3398718/

the issue is that the stock firmware does not have support for booting into edl from fastboot but mine do (debian, openwrt)

**Comment by faroukrmt** [comment]
no, it did't work :( ... reboot again into bootloader ... how I excute the edl command for openwrt firmware

**Comment by Mio-sha512** [comment]
The edl command for openwrt would have been `fastboot oem reboot-edl` but it seems as if all oem commands are broken for you.

I'm not sure what to do at this point as the only method of booting edl in stock is too short pins but as it never even boots into the stock firmware i have doubts about that working

**Comment by faroukrmt** [comment]
allright, If I found a solution I'll post it here. thanks

**Comment by Mio-sha512** [comment]
Just too make sure you are shorting these two right?
![IMG_20230122_162556__01](https://user-images.githubusercontent.com/35872074/213924136-1377a689-7a0a-4e9f-945f-1c7c86de4847.jpg)
Also you only need to short it shortly (1-5sek) as it boots

**Comment by faroukrmt** [comment]
yes! am shorting it and the device refuse to boot until I release the short .... then the device boot again in bootloader 
![Untitled](https://user-images.githubusercontent.com/20300548/213924946-13ea20b4-631b-4c7e-bf2f-ca2815b123b4.png)

can't find other points in the internet

**Comment by faroukrmt** [comment]
update: after secessfully erasing aboot, boot and rootfs ... the device rebooted into (USB\VID_05C6&PID_9006&MI_00\6&2D390D85&0&0000) Qualcomm HS-USB Diagnostics 9006
![image](https://user-images.githubusercontent.com/20300548/213928012-c0bdf1c0-e45f-4fa8-a92a-bbd6bd371d46.png)
I think its a part of the resolution

**Comment by faroukrmt** [comment]
i can see all partitions 
![image](https://user-images.githubusercontent.com/20300548/213930330-9c0453aa-7cdc-40c5-a5b0-9be71e361864.png)
the best way is to reflash the device partitions one by one from your ipenwrt .. one by one 
![image](https://user-images.githubusercontent.com/20300548/213930411-9950e351-0a84-4af8-bd66-7a1f35c0d9ab.png)
any safe suggestions ?

**Comment by Mio-sha512** [comment]
Since you now know how to force the stick to boot into edl I think it's safe enough to just use the block0 flasher with either the stock one or the others.

Also this is great to know for when other people (maybe) have the same problem.

**Comment by faroukrmt** [comment]
success ! simply by writing the dump file with EMMCRAW tool.
bonus : since uz801 had a very bad web interface,  I flashed the uf896 dump instead and write my qcn ...- the modem boot -web interface works -wifi and rndis  works  .... but led lights, sim and cellular not working.
manipulating the flash may lead to a succussful web interface swap.
